apiVersion: v1
appVersion: "1.0.0-M3"
description: A Helm chart for Eclipse Ditto
name: eclipse-ditto
version: 0.6.1
home: www.eclipse.org/ditto
sources:
- https://github.com/eclipse/ditto
- https://github.com/kiwigrid/helm-charts/tree/master/charts/eclipse-ditto
icon: https://www.eclipse.org/ditto/images/ditto.svg
maintainers:
- name: axdotl
  email: axel.koehler@kiwigrid.com
