version: '3.0'

services:
  mongodb:
    image: docker.io/mongo:3.4
    networks:
      default:
        aliases:
          - mongodb
    command: mongod --storageEngine wiredTiger --noscripting
    user: mongodb
    environment:
       TZ: Europe/Berlin

  policies:
    image: docker.io/eclipse/ditto-policies:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    command: sh -c "java -jar /starter.jar $_JAVA_OPTIONS"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Dditto.cluster.become-leader=true

  things:
    image: docker.io/eclipse/ditto-things:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    command: sh -c "sleep 10; java -jar /starter.jar $_JAVA_OPTIONS"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError -Xtune:virtualized

  things-search:
    image: docker.io/eclipse/ditto-things-search:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    command: sh -c "sleep 15; java -jar /starter.jar $_JAVA_OPTIONS"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError -Xtune:virtualized

  gateway:
    image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    command: sh -c "sleep 20; java -jar /starter.jar $_JAVA_OPTIONS"
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - ENABLE_DUMMY_AUTH=true
#      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=10.55.32.35

  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui:v2.2.9
    volumes:
       - ../documentation/src/main/resources/openapi:/usr/share/nginx/html/openapi:ro
       - ../documentation/src/main/resources/images:/usr/share/nginx/html/images:ro
       - ./swagger-index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - API_URL=/apidoc/openapi/ditto-api-1.yml

  nginx:
    image: docker.io/nginx:1.13-alpine
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
       - ./nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
       - ./index.html:/etc/nginx/html/index.html:ro
       - ../documentation/src/main/resources/images:/etc/nginx/html/images:ro
    ports:
      - "8888:80"
    depends_on:
      - gateway
      - swagger-ui
