apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ditto-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
#  storageClassName: <YOUR_STORAGE_CLASS>
