# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
name: push-dockerhub-nightly

on:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2 # setup buildx in order to do build and push multi-architecture images
      -
        name: Inspect buildx builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eclipsedittobot
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Branch name
        id: branch_name
        run: |
          echo "IMAGE_TAG=nightly" >> $GITHUB_ENV
      -
        name: Building + pushing Docker images for tag
        run: |
          echo $IMAGE_TAG
      -
        name: Build and push ditto-policies
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-release
          platforms: linux/amd64,linux/arm64
          build-args: |
            SERVICE_STARTER=ditto-policies-service
            SERVICE_VERSION=0-SNAPSHOT
          pull: true
          push: true
          tags: |
            eclipse/ditto-policies:${{ env.IMAGE_TAG }}
      -
        name: Build and push ditto-things
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-release
          platforms: linux/amd64,linux/arm64
          build-args: |
            SERVICE_STARTER=ditto-things-service
            SERVICE_VERSION=0-SNAPSHOT
          pull: true
          push: true
          tags: |
            eclipse/ditto-things:${{ env.IMAGE_TAG }}
      -
        name: Build and push ditto-concierge
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-release
          platforms: linux/amd64,linux/arm64
          build-args: |
            SERVICE_STARTER=ditto-concierge-service
            SERVICE_VERSION=0-SNAPSHOT
          pull: true
          push: true
          tags: |
            eclipse/ditto-concierge:${{ env.IMAGE_TAG }}
      -
        name: Build and push ditto-gateway
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-release
          platforms: linux/amd64,linux/arm64
          build-args: |
            SERVICE_STARTER=ditto-gateway-service
            SERVICE_VERSION=0-SNAPSHOT
          pull: true
          push: true
          tags: |
            eclipse/ditto-gateway:${{ env.IMAGE_TAG }}
      -
        name: Build and push ditto-thingsearch
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-release
          platforms: linux/amd64,linux/arm64
          build-args: |
            SERVICE_STARTER=ditto-thingsearch-service
            SERVICE_VERSION=0-SNAPSHOT
          pull: true
          push: true
          tags: |
            eclipse/ditto-things-search:${{ env.IMAGE_TAG }}
      -
        name: Build and push ditto-connectivity
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-release
          platforms: linux/amd64,linux/arm64
          build-args: |
            SERVICE_STARTER=ditto-connectivity-service
            SERVICE_VERSION=0-SNAPSHOT
          pull: true
          push: true
          tags: |
            eclipse/ditto-connectivity:${{ env.IMAGE_TAG }}
      -
        name: Build and push ditto-ui
        uses: docker/build-push-action@v3
        with:
          context: ./ui
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            eclipse/ditto-ui:${{ env.IMAGE_TAG }}
