# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
name: Release and publish Helm chart

on:
  workflow_dispatch:
    inputs:
      chartVersion:
        description: 'Helm chart version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Package and push Ditto Helm chart to Docker Hub
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          repository: eclipse
          name: ditto
          tag: ${{ inputs.chartVersion }}
          path: deployment/helm/ditto
          registry: registry-1.docker.io
          registry_username: eclipsedittobot
          registry_password: ${{ secrets.DOCKER_HUB_TOKEN }}
