apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
{{ (.Files.Glob "files/nginx/nginx.conf").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
{{ (.Files.Glob "files/nginx/index.html").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cors
data:
{{ (.Files.Glob "files/nginx/nginx-cors.conf").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-htpasswd
data:
{{ (.Files.Glob "files/nginx/nginx.htpasswd").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-ui-api
data:
{{ (.Files.Glob "files/openapi/*").AsConfig | indent 2 }}