apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eclipse-ditto.fullname" . }}-mongodb-secret
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-mongodb-secret
{{ include "eclipse-ditto.labels" . | indent 4 }}
type: Opaque
data:
  concierge-uri: {{ .Values.dbconfig.concierge.uri | b64enc | quote}}
  connectivity-uri: {{ .Values.dbconfig.connectivity.uri  | b64enc | quote}}
  things-uri: {{ .Values.dbconfig.things.uri  | b64enc | quote}}
  searchDB-uri: {{ .Values.dbconfig.searchDB.uri  | b64enc | quote}}
  policies-uri: {{ .Values.dbconfig.policies.uri  | b64enc | quote}}
