apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  concierge-uri: {{ .Values.mongodb.apps.concierge.uri | b64enc | quote}}
  connectivity-uri: {{ .Values.mongodb.apps.connectivity.uri  | b64enc | quote}}
  things-uri: {{ .Values.mongodb.apps.things.uri  | b64enc | quote}}
  searchDB-uri: {{ .Values.mongodb.apps.searchDB.uri  | b64enc | quote}}
  policies-uri: {{ .Values.mongodb.apps.policies.uri  | b64enc | quote}}
