{{- if .Values.policies.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.policies.name }}
  labels:
    app: {{ .Values.policies.name }}
    app.kubernetes.io/name: {{ .Values.policies.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.policies.name }}
  replicas: {{ .Values.policies.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.policies.name }}
        actorSystemName: {{ .Values.akka.actorSystemName }}
    spec:
      containers:
        - name: {{ .Values.policies.name }}
          image: "{{ .Values.policies.image.repository }}:{{ .Values.policies.image.tag }}"
          imagePullPolicy: {{ .Values.policies.image.imagePullPolicy }}
          command: ["java"]
          args: ["-jar", "/opt/ditto/starter.jar"]
          ports:
            - name: akka-remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: akka-mgmt-http
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.akka.mgmthttp.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.akka.remoting.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          resources:
            requests:
              memory: "{{ .Values.policies.memory }}"
            limits:
              # cpu: "" no cpu limit to avoid CFS scheduler limits see https://doc.akka.io/docs/akka/snapshot/additional/deploy.html#in-kubernetes
              memory: "{{ .Values.policies.memory }}"
          env:
            - name: K8S_NAMESPACE
              value: {{.Release.Namespace}}
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: OPENJ9_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError{{ if .Values.mongodb.apps.policies.ssl }} -Dorg.mongodb.async.type=netty{{ end }}"
            - name: MONGO_DB_SSL_ENABLED
              value: "{{ if .Values.mongodb.apps.policies.ssl }}true{{ else }}false{{ end }}"
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: policies-uri
{{- if .Values.policies.networkPolicy.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.policies.name }}-policy
  namespace: {{.Release.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.policies.name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
# Allow access from concierge
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.concierge.name }}
    ports:
    - protocol: TCP
      port: 8080
# Allow inner cluster communication
  - from:
    - podSelector:
        matchLabels:
          actorSystemName: {{ .Values.akka.actorSystemName }}
    ports:
    - protocol: TCP
      port: {{ .Values.akka.remoting.port }}
    - protocol: TCP
      port: {{ .Values.akka.mgmthttp.port }}
# Open all egress
  egress:
  - {}
{{- end }}
{{- end }}