{{- if .Values.rbac.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "eclipse-ditto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}
{{ include "eclipse-ditto.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
{{- end -}}
