{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eclipse-ditto.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}
{{ include "eclipse-ditto.labels" . | indent 4 }}
{{- end -}}
