{{- if .Values.swaggerui.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "eclipse-ditto.fullname" . }}-swaggerui
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-swaggerui
{{ include "eclipse-ditto.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-swaggerui
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-nginx
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 8080
{{- end }}
